import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

import { generateImages } from '#scripts/generate-images.ts';
import { generateThemeInit } from '#scripts/generate-theme-init.ts';

export default defineConfig(({ command }) => ({
  build: {
    // Preserve native light-dark(), which follows the runtime color-scheme value.
    cssTarget: 'esnext',
    minify: 'oxc',
  },
  plugins: [
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateThemeInit,
      enforce: 'pre',
      name: 'generate-theme-init',
    },
    {
      // The client build reuses the images generated by the preceding SSR build.
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateImages,
      enforce: 'pre',
      name: 'generate-images',
    },
    sveltekit(),
  ],
  ssr: {
    noExternal: ['@lucide/svelte'],
  },
}));
