import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

import { generateFavicon } from '#scripts/generate-favicon.ts';
import { generateImages } from '#scripts/generate-images.ts';
import { generateInitScripts } from '#scripts/generate-init-scripts.ts';

export default defineConfig(({ command }) => ({
  build: {
    // Preserve native light-dark(), which follows the runtime color-scheme value.
    cssTarget: 'esnext',
    minify: 'oxc',
  },
  plugins: [
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateFavicon,
      enforce: 'pre',
      name: 'generate-favicon',
    },
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateInitScripts,
      enforce: 'pre',
      name: 'generate-init-scripts',
    },
    {
      // The client build reuses the images generated by the preceding SSR build.
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateImages,
      enforce: 'pre',
      name: 'generate-images',
    },
    sveltekit(),
  ],
  ssr: {
    noExternal: ['@lucide/svelte'],
  },
}));
