import adapter from '@sveltejs/adapter-static';
import { sveltekit } from '@sveltejs/kit/vite';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vite';
import { z } from 'zod';

import { generateFavicon } from '#scripts/generate-favicon.ts';
import { generateGallery } from '#scripts/generate-gallery.ts';
import { generateImages } from '#scripts/generate-images.ts';
import { generateInitScripts } from '#scripts/generate-init-scripts.ts';
import { optimizeStaticOutput } from '#scripts/optimize-static-output.ts';

const basePathSchema = z.union([z.literal(''), z.templateLiteral(['/', z.string()])]);
const basePath = basePathSchema.safeParse(process.env.BASE_PATH ?? '');
if (!basePath.success) {
  throw new Error('BASE_PATH must begin with a slash.');
}

export default defineConfig(({ command }) => ({
  build: {
    // Preserve native light-dark(), which follows the runtime color-scheme value.
    cssTarget: 'esnext',
    minify: 'oxc',
  },
  plugins: [
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateGallery,
      enforce: 'pre',
      name: 'generate-gallery',
    },
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateFavicon,
      enforce: 'pre',
      name: 'generate-favicon',
    },
    {
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateInitScripts,
      enforce: 'pre',
      name: 'generate-init-scripts',
    },
    {
      // The client build reuses the images generated by the preceding SSR build.
      applyToEnvironment: (environment) => command === 'serve' || environment.name === 'ssr',
      buildStart: generateImages,
      enforce: 'pre',
      name: 'generate-images',
    },
    sveltekit({
      adapter: optimizeStaticOutput(
        adapter({
          assets: 'dist',
          pages: 'dist',
        }),
        'dist',
      ),
      csp: {
        directives: {
          'base-uri': ['self'],
          'object-src': ['none'],
          'script-src': ['self'],
        },
        mode: 'hash',
      },
      // These small stylesheets are cheaper to include in the first response.
      inlineStyleThreshold: 20_000,
      paths: {
        base: basePath.data,
      },
      preprocess: vitePreprocess(),
    }),
  ],
  ssr: {
    noExternal: ['@lucide/svelte'],
  },
}));
